title: Christopher Francisque
position: Master of Computer Science | ML Researcher
affiliation: University of Pennsylvania
email: chrisfra (at) seas.upenn.edu
keywords: machine learning, deep learning, parameter-efficient fine-tuning, research
github_link: https://github.com/chrisfrancisque
linkedin: https://www.linkedin.com/in/christopherfrancisque
avatar: ./assets/img/profile.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: ML Researcher and Graduate Student specializing in parameter-efficient fine-tuning and deep learning systems. Security clearance holder.
canonical: https://christopherfrancisque.com/
remote_theme: yaoyao-liu/minimal-light